# run this file as: 'docker compose up'
services:
  web:
    build:
      context: .
    environment:
      # this is needed for hot reload (at least in windows)
      # environment variables defined in Dockerfile will be used both in
      # docker build and in the container, while in compose.yaml will just
      # be used in the containers
      - CHOKIDAR_USEPOLLING=true

    ports:
      - 5174:5174

    volumes:
      - .:/app
      - /app/node_modules
